### ISSUE TITLE
Lacking start script

### ISSUE THREAD

**Issue by Alacho2** [Jack-Works/generate-matrix-js-sdk-type#1]
The ./dist/index.js is lacking in the project

**Comment by Jack-Works** [comment]
Oh you can build the script by tsc or run it directly by `ts-node -T src/index.ts`

By the way, the matrix-js-sdk should be in the ../matrix-js-sdk/

**Comment by Jack-Works** [comment]
And if you're looking for a simpler but somehow typed API, you can use https://github.com/turt2live/matrix-js-bot-sdk this project.

**Comment by Alacho2** [comment]
Sweet, that's very nice. I'm trying to fork your code to function for Flow.JS :)

**Comment by Jack-Works** [comment]
> Sweet, that's very nice. I'm trying to fork your code to function for Flow.JS :)

Hi, these days matrix-js-sdk has changed a lot. It coverts all files to the ES6 module and I help them to convert all classes to ES6 class (still in progress). This will make static analysis easier. Many of the tricks in this project is for CommonJS and ES5 class and this is no longer needed.

After all the classes upgraded to ES6, I will review this project and up it to date.

**Comment by Jack-Works** [comment]
On the other way, @huan has provided a TypeScript definition written by hand (https://github.com/matrix-org/matrix-js-sdk/issues/983#issuecomment-593534506) you maybe want to check it out to create a flow version.

**Comment by huan** [comment]
I'm very happy to see we have this project and it's in progress!

It will be great that the codebase can move to ES6 (or TypeScript, which will be better) soon, so we can get an accurate version of the Typing definition by automatic generation instead of writing from scratch with lots of bugs like what I did in the past months. :D

**Comment by Jack-Works** [comment]
@Alacho2 @huan I have just re-generate the types for matrix-js-sdk 5.2.0, you may want to check it out

and I added the start script so I'm going to close this issue
